name: Android Design Patterns
author:
  name: Alex Lockwood
  googleplus: https://google.com/+AlexLockwood
  twitter: https://twitter.com/alexjlockwood
  stackoverflow: http://stackoverflow.com/users/844882
  flickr: http://www.flickr.com/photos/tailorransom
  github: https://github.com/alexjlockwood
  feedburner: http://feeds.feedburner.com/androiddesignpatterns

baseurl: http://www.androiddesignpatterns.com
description: 'Android Design Patterns is a website for developers who wish to better understand the Android application framework. The tutorials here emphasize proper code design and project maintainability.'

paginate: 5
excerpt_separator: <!--more-->

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables"]

relative_permalinks: false
permalink: /:year/:month/:title.html

exclude: ['README.md', 'LICENSE.txt']
